<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Authors>Soe Minn Minn</Authors>
    <Company>S16 Co. Ltd.</Company>
    <Copyright>Copyright © 2023 The Open Source Project</Copyright>
    <Title>Subtitle Tools</Title>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<DebugType>none</DebugType>
  </PropertyGroup>
  
  <ItemGroup>
	<Resource Include="icon.ico" />
	<Resource Include="Resources\*.png" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="mpv" Version="0.28.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubtitleTools\SubtitleTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="libmpv\Win32\mpv-1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libmpv\x64\mpv-1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
