<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Authors>Soe Minn Minn</Authors>
    <Company>S16 Co. Ltd.</Company>
    <Copyright>Copyright © 2023 The Open Source Project</Copyright>
    <Title>Subtitle Tools</Title>
    <UseWindowsForms>True</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<DebugType>none</DebugType>
  </PropertyGroup>
  
  <ItemGroup>
	<Resource Include="icon.ico" />
	<Resource Include="Resources\*.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubtitleTools\SubtitleTools.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include="libmpv-2.dll" CopyToOutputDirectory="PreserveNewest" Link="libmpv-2.dll" />
	</ItemGroup>

</Project>
