<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Cleaner</AssemblyName>
	<RootNamespace>SubtitleEdit.Plugins.Cleaner</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\IDialogueCommand.cs">
			<Link>Subtitle\Commands\IDialogueCommand.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\ISubtitleCommand.cs">
			<Link>Subtitle\Commands\ISubtitleCommand.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\MergeLines.cs">
			<Link>Subtitle\Commands\MergeLines.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\RemoveEmptyDialogues.cs">
			<Link>Subtitle\Commands\RemoveEmptyDialogues.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\RemoveEmptyLine.cs">
			<Link>Subtitle\Commands\RemoveEmptyLine.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\RemoveHearingText.cs">
			<Link>Subtitle\Commands\RemoveHearingText.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\SimplyStyles.cs">
			<Link>Subtitle\Commands\SimplyStyles.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\SplitLine.cs">
			<Link>Subtitle\Commands\SplitLine.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Commands\TypoFix.cs">
			<Link>Subtitle\Commands\TypoFix.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Dialogue.cs">
			<Link>Subtitle\Dialogue.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\ExtandableList.cs">
			<Link>Subtitle\ExtandableList.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\HtmlUtils.cs">
			<Link>Subtitle\HtmlUtils.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\ISubtitle.cs">
			<Link>Subtitle\ISubtitle.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\ReplaceCondition.cs">
			<Link>Subtitle\ReplaceCondition.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\StringLiteral.cs">
			<Link>Subtitle\StringLiteral.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Styler.cs">
			<Link>Subtitle\Styler.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Subtitle.Cleaner.cs">
			<Link>Subtitle\Subtitle.Cleaner.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Subtitle.cs">
			<Link>Subtitle\Subtitle.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\SubtitleHeaders.cs">
			<Link>Subtitle\SubtitleHeaders.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Tokenizer.cs">
			<Link>Subtitle\Tokenizer.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\ToolsConstants.cs">
			<Link>Subtitle\ToolsConstants.cs</Link>
		</Compile>
		<Compile Include="..\SubtitleTools\Subtitle\Utils.cs">
			<Link>Subtitle\Utils.cs</Link>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="plugin.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
